services:
  - type: web
    name: Pixel        
    env: docker
    dockerfilePath: Dockerfile       
    region: virginia         
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install -r requirements.txt
      pip install --upgrade certifi 
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: "/health"
    envVars:
      - key: DISCORD_TOKEN
        sync: false            
      - key: MONGODB_URI
        sync: false            

