services:
  - type: web
    name: Pixel
    env: python
    region: virginia 
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      aws s3 sync s3://pixel-bot-data data/ --region us-east-2
      python3 main.py
    envVars:
      - key: NEW_BOT_TOKEN
        fromSecret: NEW_BOT_TOKEN
      - key: AWS_ACCESS_KEY_ID
        fromEnv: AWS_ACCESS_KEY_ID
      - key: AWS_SECRET_ACCESS_KEY
        fromEnv: AWS_SECRET_ACCESS_KEY
      - key: AWS_S3_BUCKET
        fromEnv: AWS_S3_BUCKET
      - key: AWS_S3_REGION
        value: us-east-2
    plan: free
    disk:
      name: pixel-data
      mountPath: /data
    healthCheckPath: "/health"
    autoDeploy: true