services:
  - type: web
    name: Pixel
    runtime: python
    region: virginia
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python3 main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false  
      - key: MONGODB_URI
        sync: false
    plan: free
    healthCheckPath: "/health"
    autoDeploy: true